spring:
  datasource:
    url: jdbc:mysql://localhost:${SQL_PORT:3306}/${SQL_DATABASE:geocoder}
    username: ${SQL_USER:geocoder}
    password: ${SQL_PASSWORD:geocoder}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true