spring:
  application:
    name: geocoder-compare

  profiles:
    default: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

geocoder:
  http:
    connect-timeout: 3s
    response-timeout: 5s

  executor:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 50
    await-termination-seconds: 10

  comparison:
    reliable-threshold-meters: 100

  yandex:
    base-url: https://geocode-maps.yandex.ru/v1
    api-key: ${YANDEX_API_KEY}

  dadata:
    base-url:  https://cleaner.dadata.ru/api/v1/clean/address
    api-key: ${DADATA_API_KEY}
    secret: ${DADATA_SECRET}